name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]   # or your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install deps
        run: flutter pub get

      - name: Build (root domain)
        run: flutter build web --release --base-href /

        # If hosting at user.github.io/repo-name, replace with:
        # run: flutter build web --release --base-href /repo-name/

      - name: Add 404 + nojekyll
        run: |
          cp build/web/index.html build/web/404.html
          touch build/web/.nojekyll
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          # If you use a custom domain, set it here (optional but handy):
          cname: jatinchaudhary.com

